version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Uploading HTML files"
      - aws s3 sync dist/ s3://haddyztictactoe-bucket/ --delete --exclude "*" --include "*.html" --content-type "text/html"
      - echo "Uploading JS files"
      - aws s3 sync dist/ s3://haddyztictactoe-bucket/ --exclude "*" --include "*.js" --content-type "application/javascript"
      - echo "Uploading CSS files"
      - aws s3 sync dist/ s3://haddyztictactoe-bucket/ --exclude "*" --include "*.css" --content-type "text/css"
      - echo "Uploading everything else"
      - aws s3 sync dist/ s3://haddyztictactoe-bucket/ --exclude "*.html" --exclude "*.js" --exclude "*.css"
