version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - zip -r function.zip backend/*
      - aws s3 cp function.zip s3://codebuild-us-east-2-${AWS_ACCOUNT_ID}/function.zip
artifacts:
  files:
    - function.zip